---
title: "Log of 'willer_tc_rosmap_match' files" 
subtitle: "Project: thesis_tc_pgs_in_AD"
author: "Nathalie Nilsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
path.to.project <- paste(rprojroot::find_rstudio_root_file(), "/", sep = "")
path.to.wd <- gsub(rprojroot::find_rstudio_root_file(), "", getwd())
```
**Location of project directory:** `r path.to.project`

**Working directory relative to project:** `r path.to.wd`

## Input
Cleaned meta-analysis summary data:
```{r}
base.file <- "willer_tc_common_snps.txt"
base.file.woAPOE <- "willer_tc_common_snps_woAPOE.txt"
```

ROSMAP genetic data:
```{r}
rosmap.file <- "~/Research/Cohort_data/ROSMAP/genetic_data/imputed/rosmap_imp_eur.bim"
```

## Libraries
```{r}
library(data.table)
```

## Read data
**Willer base data**
```{r}
# Read base data
base <- fread(base.file, header = TRUE)[, -c("CHR", "BP"), with = FALSE]
base
```

```{r}
# Base data without APOE
base.woAPOE <- fread(base.file.woAPOE, header = TRUE)[, -c("CHR", "BP"), with = FALSE]
base.woAPOE
```

**PREVENT-AD target data**
```{r}
rosmap <- fread(rosmap.file, header = FALSE, 
              col.names = c("CHR", "SNP", "CM", "BP", "REF.rosmap", "ALT.rosmap"))
rosmap[, POS := list(paste(CHR, BP, sep = ":"))]
rosmap
```

## SNP discrepancies
Merge data
```{r}
m <- merge(base, rosmap, by = "POS", suffixes = c(".base", ".rosmap"))[
    ][, .(CHR, BP, SNP.base, SNP.rosmap, REF, REF.rosmap, ALT, ALT.rosmap, BETA, P)]

m.woAPOE <- merge(base.woAPOE, rosmap, by = "POS", suffixes = c(".base", ".rosmap"))[
    ][, .(CHR, BP, SNP.base, SNP.rosmap, REF, REF.rosmap, ALT, ALT.rosmap, BETA, P)]
```

Calculate number of alleles for each variant
```{r}
m$N.alleles <- apply(m[, .(REF,REF.rosmap,ALT,ALT.rosmap)], 1, function(x) length(unique(x)))
m

unique(m[, N.alleles])
```

Identify SNPs to be flipped
```{r}
correct <- m[REF == REF.rosmap & ALT == ALT.rosmap]
correct

a1a2mix <- m[REF == ALT.rosmap & ALT == REF.rosmap]
a1a2mix

flipped <- m[N.alleles == 4, ]
flipped

incorrect <- m[N.alleles == 3, 
               ][, EXCL_REASON := "Multiple alleles"]
incorrect

nrow(correct) + nrow(a1a2mix) + nrow(flipped) + nrow(incorrect) == nrow(m)
```

## Write data
```{r}
dir.create("willer_tc_rosmap_match")
fwrite(m[!SNP.rosmap %in% incorrect[, SNP.rosmap] , .(SNP = SNP.rosmap, REF, P, BETA, ALT)], 
       file = "willer_tc_rosmap_match/willer_tc_rosmap_match.txt", sep = "\t")
fwrite(m[!SNP.rosmap %in% incorrect[, SNP.rosmap], .(SNP = SNP.rosmap, P)], 
       file = "willer_tc_rosmap_match/willer_tc_rosmap_match_snps_clump.txt", sep = "\t")
fwrite(m.woAPOE[!SNP.rosmap %in% incorrect[, SNP.rosmap] , .(SNP = SNP.rosmap, REF, P, BETA, ALT)], 
       file = "willer_tc_rosmap_match/willer_tc_rosmap_match_woAPOE.txt", sep = "\t")
fwrite(flipped[, .(SNP.rosmap)], 
       file = "willer_tc_rosmap_match/willer_tc_rosmap_match_SNPsFlip.txt", 
       sep = "\t", col.names = FALSE)
fwrite(incorrect, 
       file = "willer_tc_rosmap_match/willer_tc_rosmap_match_SNPsExcl.txt", 
       sep = "\t", col.names = TRUE)
```