---
title: "PG scoring of PRAD_2019 data based on Willer TC results"
subtitle: "Project: thesis_tc_pgs_in_AD"
author: "Nathalie Nilsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig_height: 5.2
    fig_width: 6.1
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
path.to.project <- paste(rprojroot::find_rstudio_root_file(), "/", sep = "")
path.to.wd <- gsub(rprojroot::find_rstudio_root_file(), "", getwd())
```
**Location of project directory:** `r path.to.project`

**Working directory relative to project:** `r path.to.wd`

## Input

#### Target data
```{r}
target.file         <- "~/Research/Cohort_data/ADPREVENT/Genetic_data/PRAD_2019/imputed/prad_2019_imp_eur" # .bed; .bim & .fam file
```

#### Base data
Paths relative to project base directory:
```{r}
base.file               <- "data/willer/willer_tc_prad_match/willer_tc_prad_match_woAPOE.txt" # summary file with header
base.file.snps.clump    <- "data/willer/willer_tc_prad_match/willer_tc_prad_match_snps_clump.txt"
base.file.flip.snps     <- "data/willer/willer_tc_prad_match/willer_tc_prad_match_SNPsFlip.txt" # file with SNPs to flip
```

#### Scoring parameters
```{r}
# column numbers for SNP, A1, P and BETA
base.file.cols 	    <- c(1, 2, 3, 4)

# p-value thresholds
base.file.ps	    <- c(1e-100, 1e-50, 1e-40, 1e-30, 1e-20, 1e-10, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 0.05, 0.1, 0.5, 1)

# Clumping parameters
clump.p1 <- 1 # index variant p-value threshold
clump.p2 <- 1 # clumped variant p-value threshold
clump.kb <- 250 # clump kb radius
clump.r2 <- 0.1 # r^2 threshold
```

#### Output parameters
```{r}
base.file.name      <- "willer_tc"
output.name 	<- "prad_tc_pgs_woAPOE"
```

## Libraries
Note: also depends on PLINK
```{r}
library(tidyverse)
```

## Set up directory for analysis
```{r}
dir.create("target_files", recursive = TRUE)
dir.create("score_files")

file.copy(paste(path.to.project, base.file, sep = ""), "base_file.txt")
file.copy(paste(path.to.project, base.file.flip.snps, sep = ""), "snps_flip.txt")
file.copy(paste(path.to.project, base.file.snps.clump, sep = ""), "snps_clump.txt")
```

## Pruning of data
```{r}
system(paste("plink --bfile \"", target.file, "\" --extract base_file.txt --make-bed --out temp", sep = ""))
cat(readLines("temp.log"), sep = "\n")

system(paste("plink --bfile temp --clump snps_clump.txt --clump-p1 ", clump.p1, " --clump-p2 ", clump.p2, " --clump-kb ", clump.kb, " --clump-r2 ", clump.r2, " --out target_files/", output.name, "_clump", sep = ""))
cat(readLines(paste("target_files/", output.name, "_clump.log", sep = "")), sep = "\n")

clumped <- read.table(paste("target_files/", output.name, "_clump.clumped", sep = ""), header = TRUE)

snps.incl <- clumped$SNP %>%
    unlist() %>%
    as.character()
write.table(data.frame(snps.incl), 
            file = paste("target_files/", output.name, "_inclSNPs.txt", sep = ""), 
            col.names = FALSE, row.names = FALSE, quote = FALSE)

system(paste("plink --bfile \"", target.file, "\" --extract target_files/", output.name, "_inclSNPs.txt --make-bed --out target_files/", output.name, "_LDPRUNED", sep = ""))
cat(readLines(paste("target_files/", output.name, "_LDPRUNED.log", sep = "")), sep = "\n")

```

## Range file
Creates a range file with the p cut-offs
```{r}
my.range.list <- cbind(label = c(paste("S0", 1:9, sep = ""), paste("S", 10:length(base.file.ps), sep = "")),
                       pmin = rep(0, length(base.file.ps)),
                       pmax = base.file.ps)
write.table(my.range.list, file = paste("scoring_range.txt", sep = ""), 
            row.names = FALSE, quote = FALSE, sep = "\t")
```

## Scoring
```{r}
system(paste("plink --bfile target_files/", output.name, "_LDPRUNED --flip snps_flip.txt --q-score-range scoring_range.txt base_file.txt 1 3 header --score base_file.txt 1 2 4 header --out score_files/", output.name, sep = ""))
cat(readLines(paste("score_files/", output.name, ".log", sep = "")), sep = "\n")

```

```{r}
file.remove("base_file.txt", "plink.exe", 'temp.bim', "temp.bed", "temp.fam", "temp.log")
```

