---
title: "TC pgs effect on conversion rate in ADNI"
subtitle: "Project: thesis_tc_pgs_in_AD"
author: "Nathalie Nilsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig_height: 6
    fig_width: 6.5
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
path.to.project <- paste(rprojroot::find_rstudio_root_file(), "/", sep = "")
path.to.wd <- gsub(rprojroot::find_rstudio_root_file(), "", getwd())
```
**Location of project directory:** `r path.to.project`

**Working directory relative to project:** `r path.to.wd`

## Notes
...

## Input
Relative to project base directory:
```{r}
pheno.file <- "data/adni/adni_summary_data.txt"
```

## Libraries
```{r}
library(tidyverse)
library(gridExtra)
library(survival)
library(ggfortify)
library(survminer)

source(paste(path.to.project, "scripts/project_functions.R", sep = ""))
source("~/Research/Methods/R Programming/Scripts/Stats/Quantiles.R")
```

## Data
```{r}
pheno <- read.within.project.h(pheno.file)
colnames(pheno)
```

```{r}
pheno$pgs.qs <- my.quantile.function(pheno$tc.pgs, 3)

pheno.f <- filter(pheno, fh.ad == 1 & !is.na(tc.pgs) & bl.atn.a == 1 & bl.dx %in% c(1, 2)) %>%
    select(iid, pgs.qs, sex.f, ad.conv.time, ad.conv)
```


### Survival analysis
```{r}
my.fit.0 <- survfit(Surv(ad.conv.time, ad.conv) ~ pgs.qs, data = pheno.f)
my.diff.0 <- survdiff(Surv(ad.conv.time, ad.conv) ~ pgs.qs, data = pheno.f, rho = 0.5)
my.diff.0

pval.0 <- pchisq(my.diff.0$chisq, length(my.diff.0$n)-1, lower.tail = FALSE) %>% signif(4)

ggsurvplot(my.fit.0, ylim = c(0, 1), surv.size = 1, conf.int = FALSE, risk.table = TRUE, risk.table.y.text = FALSE,
           break.time.by = 12)
```

## Save data
```{r}
save(list = c("my.fit.0", "my.diff.0", "pval.0", "pheno.f"), 
     file = "adni_conv.RData")
```

