---
title: 'Amyloid pathology ~ TC-PGS'
author: "Nathalie Nilsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig.width: 6.5
    highlight: textmate
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R version
```{r, echo=FALSE}
R.version
```

## Project
```{r}
path.to.project <- paste(rprojroot::find_rstudio_root_file(), "/", sep = "")
path.to.project
```

## Input

#### PREVENT-AD data
```{r}
prad.ab42.data <- "analyses/preventad/5_abeta_pathology/prad_csf_ab42.RData"
prad.r.data <- "analyses/preventad/5_abeta_pathology/prad_csf_ab42.40.RData"
prad.pet.data <- "analyses/preventad/5_abeta_pathology/prad_pet_ab.RData"
```

#### ADNI data
```{r}
adni.data <- "analyses/adni/v2_prad_snps/5_abeta_pathology/adni_csf_ab.RData"
```

#### Output
```{r}
output.name <- "ab_pathology"
```

## Libraries
```{r}
library(tidyverse)
#library(gridExtra)
library(cowplot)

source("~/Research/Projects/thesis_tc_pgs_in_AD/scripts/project_functions.R")
source("~/PhD_milestones/PhD thesis/figures/plot_parameters_for_thesis.R")
```

## Data

### PREVENT-AD
```{r}
load(paste(path.to.project, prad.ab42.data, sep = ""), verbose = TRUE)
p.ab42 <- csf.cc %>%
    mutate(data.type = "CSF AB-42")
p.ab42.desc <- desc.stat
rm(csf.cc, csf.statinfree, desc.stat)
```

```{r}
load(paste(path.to.project, prad.r.data, sep = ""), verbose = TRUE)
p.r <- csf.cc %>%
    mutate(data.type = "CSF AB-42/AB-40 ratio")
p.r.desc <- desc.stat
rm(csf.cc, csf.statinfree, desc.stat)
```

```{r}
load(paste(path.to.project, prad.pet.data, sep = ""), verbose = TRUE)
p.pet <- pet.cc %>%
    mutate(data.type = "AB PET")
p.pet.desc <- desc.stat
rm(pet.cc, desc.stat)
```

### ADNI
```{r}
load(paste(path.to.project, adni.data, sep = ""), verbose = TRUE)
a.ab42 <- csf.f %>%
    mutate(data.type = "CSF AB-42")
a.ab42.desc <- desc.stat
rm(desc.stat, csf.f)
```

## Plotting

#### PRAD CSF AB42
```{r, fig.height=3.5}
p.prad.ab42 <- ggplot(p.ab42, aes(tc.pgs, csf.ab42, color = sex, shape = sex)) +
    geom_point(size = point.size) +
    scale_shape_manual(values = c(0, 5)) +
    geom_smooth(method = "lm", alpha = 0.2, aes(fill = sex)) +
    scale_color_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_fill_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    facet_grid(~data.type) +
    my.theme.bar.no.legend +
    labs(title = expression(paste("(A) PREVENT-AD CSF A", beta, " levels", sep = ""))) +
    ylab(expression(paste("CSF A", beta, "-42 [pg/ml]", sep = ""))) +
    xlab("Standardized TC-PGS")
p.prad.ab42
```

#### PRAD CSF AB42/40 ratio
```{r}
p.prad.r <- ggplot(p.r, aes(tc.pgs, csf.ab42.40, color = sex, shape = sex)) +
    geom_point(size = point.size) +
    geom_smooth(method = "lm", alpha = 0.2, aes(fill = sex)) +
    scale_color_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_fill_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_shape_manual(values = c(0, 5)) +
    facet_grid(~data.type) +
    my.theme.bar.no.legend +
    labs(title = " ") +
    ylab(expression(paste("CSF A", beta, "-42/A", beta, "-40 [ratio]", sep = ""))) +
    xlab("Standardized TC-PGS")
p.prad.r
```

#### PRAD amyloid PET
```{r}
p.pet$sex <- factor(p.pet$sex, levels = c("Male", "Female"))
p.pet$petab.pos <- factor(p.pet$petab.pos, levels = c(0, 1), labels = c("AB(-)", "AB(+)"))
```

```{r}
p.prad.pet.neg <- ggplot(filter(p.pet, petab.pos == "AB(-)"), aes(tc.pgs, petab, color = sex, shape = sex)) +
    geom_point(size = point.size) +
    geom_smooth(method = "lm", alpha = 0.2, aes(fill = sex)) +
    scale_color_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_fill_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_shape_manual(values = c(0, 5)) +
    my.theme.bar.no.legend +
    facet_grid(~petab.pos) +
    labs(title = expression(paste("(B) PREVENT-AD A", beta, " PET", sep = ""))) +
    ylab(expression(paste("A", beta, " [SUVR]"))) +
    xlab("Standardized TC-PGS")
p.prad.pet.neg

p.prad.pet.pos <- ggplot(filter(p.pet, petab.pos == "AB(+)"), aes(tc.pgs, petab)) +
    geom_point(size = point.size, shape = 15) +
    geom_smooth(method = "lm", alpha = 0.2, color = "black") +
    my.theme.bar +
    facet_grid(~petab.pos) +
    labs(title = " ") +
    ylab(expression(paste("A", beta, " [SUVR]"))) +
    xlab("Standardized TC-PGS")
p.prad.pet.pos
```

#### ADNI CSF AB42
```{r}
p.adni.ab42 <- ggplot(a.ab42, aes(tc.pgs, csf.ab42, color = sex, shape = sex)) +
    geom_point(size = point.size) +
    geom_smooth(method = "lm", alpha = 0.2, aes(fill = sex)) +
    scale_color_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_fill_manual(values = c("#1f3c6dff", "#f5dd4dff")) +
    scale_shape_manual(values = c(0, 5)) +
    facet_grid(~statin) +
    my.theme.bar.no.legend +
    scale_y_continuous(trans = "log2") +
    labs(title = expression(paste("(C) ADNI CSF A", beta, "-42 levels", sep = ""))) +
    ylab(expression(paste("CSF A", beta, "-42 [pg/ml] (log2 scale)", sep = ""))) +
    xlab("Standardized TC-PGS")
p.adni.ab42
```

#### Summary plot
```{r, fig.height=8.5, fig.width=6}
# first align the top-row plot (p3) with the left-most plot of the
# bottom row (p1)
plots <- align_plots(p.prad.ab42, p.prad.pet.neg, p.adni.ab42, align = 'v', axis = 'l')
# then build the bottom row
top <- plot_grid(plots[[1]], p.prad.r,
                 plots[[2]], p.prad.pet.pos, 
                 nrow = 2, ncol = 2)

# then combine with the top row for final plot
p <- plot_grid(top, plots[[3]], ncol = 1, rel_heights = c(2, 1))
p
```

```{r}
ggsave(paste(output.name, ".pdf", sep = ""), plot = p, width = 4.5, height = 7)
```

