---
title: "Log of 'all_descriptives'" 
subtitle: "Project: thesis_tc_pgs_in_AD"
author: "Nathalie Nilsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig_height: 5.2
    fig_width: 6.1
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
path.to.project <- paste(rprojroot::find_rstudio_root_file(), "/", sep = "")
path.to.wd <- gsub(rprojroot::find_rstudio_root_file(), "", getwd())
```
**Location of project directory:** `r path.to.project`

**Working directory relative to project:** `r path.to.wd`

## Input
```{r}
prad.file <- "data/preventad/prad_summary_data.txt"
adni.file <- "data/adni/adni_summary_data.txt"
roma.file <- "data/rosmap/rosmap_summary_data.txt"
```

## Libraries
```{r}
library(tidyverse)
library(psych)

source(paste(path.to.project, "scripts/project_functions.R", sep = ""))
```

## Data 
```{r}
prad <- read.within.project.h(prad.file) %>%
    mutate(cohort = "prad")
colnames(prad)

# create an age column with as much data as possible (if baseline age not available, the youngest age for each individual is selected)
prad.age <- select(prad, iid, contains("age"))
prad$age <- apply(select(prad, bl.age.y,tc.age,csf.age, petab.age,pettau.age), 1, function(x) {
    if(!is.na(x["bl.age.y"])) {x["bl.age.y"]}
    else {min(x, na.rm = TRUE)}
})

prad.age <- select(prad, iid, contains("age"))

prad[prad == Inf] <- NA

# convert factors to numeric
levels(prad$sex)
prad$sex.f <- abs(as.numeric(prad$sex) - 2)
sum(prad$sex.f, na.rm = TRUE)

prad$apoe4.status <- as.numeric(prad$apoe4.status) - 1
prad$statin <- as.numeric(prad$statin) - 1

# select columns
prad.s <- prad %>%
    select(iid, sex.f, apoe4.status, statin, age, 
           tc.age, tc.mM, tc.pgs, 
           csf.age, csf.ab42, csf.ab40, csf.tau, csf.ptau, 
           petab, petab.age, pettau.etx, pettau.age, cohort)
```

```{r}
adni <- read.within.project.h(adni.file) %>%
    filter(!is.na(tc.pgs) & fh.ad == 1) %>%
    mutate(cohort = "adni")
colnames(adni)

# create age columns
adni$csf.age <- apply(adni, 1, function(x) {
    if(!is.na(x["bl.csf.ptau"])) {x["bl.age"]}
    else {NA}
}) %>% as.numeric()
adni$ci.age <- apply(adni, 1, function(x) {
    if(!is.na(x["lv.ci"])) {x["lv.age"]}
    else {NA}
}) %>% as.numeric()

adni.s <- adni %>%
    select(iid, sex.f, apoe4.status, statin = statin.sc.bl, age = bl.age,
           tc.age, tc.mM = sc.tc.mM, tc.pgs, 
           csf.age, csf.ab42 = bl.csf.ab42, csf.tau = bl.csf.tau, csf.ptau = bl.csf.ptau, 
           ci.age, ci = lv.ci, cohort)
```

```{r}
roma <- read.within.project.h(roma.file) %>%
    mutate(cohort = "roma")
colnames(roma)

# create age column
roma$ci.age <- apply(roma, 1, function(x) {
    if(!is.na(x["cog.ci"])) {x["age"]}
    else {NA}
}) %>% as.numeric()

roma.s <- roma %>%
    select(iid, sex.f, apoe4.status, age,
           ci.age, ci = cog.ci, tc.pgs, cohort)
```

### Combined
```{r}
m <- merge.data.frame(prad.s, adni.s, all = TRUE) %>%
    merge.data.frame(roma.s, all = TRUE)
nrow(m) == (nrow(adni.s) + nrow(prad.s) + nrow(roma.s))
```

## Descriptives

### Summary statistics
```{r}
d <- describeBy(m, "cohort")
s <- d[["prad"]] %>%
    merge.data.frame(d[["adni"]], by = "row.names", 
                     suffixes = c("_prad", "_adni")) %>%
    merge.data.frame(d[["roma"]], by.x = "Row.names", by.y = "row.names") %>%
    select(variable = "Row.names", 
           n_prad, mean_prad, sd_prad, 
           n_adni, mean_adni, sd_adni, 
           n_roma = n, mean_roma = mean, sd_roma = sd)
s
```

```{r}
s[, c(3,4,6,7,9,10)] <- round(s[, c(3,4,6,7,9,10)], 2)
s
```

### P-values

#### Chi-square tests
```{r}
disc_variables <- c("apoe4.status", "ci", "sex.f", "statin")
c.list <- list()
for(i in 1:length(disc_variables)) {
    c.list[[disc_variables[i]]] <- chisq.test(m[, "cohort"], m[, disc_variables[i]])$p.value 
}
c.df <- data.frame(p = unlist(c.list)) %>%
    rownames_to_column(var = "variable")
```

#### T-tests
```{r}
cont_variables_t <- c("tc.mM", "tc.age", "csf.ab42", "csf.ptau", "csf.tau", "ci.age", "csf.age")
t.list <- list()
for (i in 1:length(cont_variables_t)) {
    t.list[[cont_variables_t[i]]] <- t.test(as.formula(paste(cont_variables_t[i], "~", "cohort")), data = m)$p.value 
}
t.df <- data.frame(p = unlist(t.list)) %>%
    rownames_to_column("variable")
```

#### ANOVAs
```{r}
cont_variables_a <- c("tc.pgs", "age")
a.df <- data.frame(variable = c("tc.pgs", "age"), 
                   p = c(anova(lm(tc.pgs~cohort, m))$`Pr(>F)`[1], 
                         anova(lm(age~cohort, m))$`Pr(>F)`[1]))
TukeyHSD(aov(lm(age~cohort, m)))
```

#### All
```{r}
p <- rbind.data.frame(c.df, t.df, a.df)
```

### Final table
```{r}
final <- merge.data.frame(s, p, all.x = TRUE)
final
```

## write data
```{r}
write.table(final, file = "all_descriptives.txt", 
            row.names = FALSE, quote = FALSE, sep = "\t")
```

